sudo: true
language: python
matrix:
  include:
    - os: osx
      env: TOXENV=py36
    - os: osx
      env: TOXENV=py27
    - os: linux
      python: "2.7"
      dist: trusty
    - os: linux
      python: "3.4"
      dist: trusty
    - os: linux
      python: "3.5"
      dist: trusty
    - os: linux
      python: "3.6"
      dist: trusty
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libunwind8; fi
  - if [ ( $TRAVIS_OS_NAME == osx ) && ( $TOXENV == py36 ) ]; then brew update; fi
  - if [ ( $TRAVIS_OS_NAME == osx ) && ( $TOXENV == py36 ) ]; then brew install python3; fi
install:
  - pip install codecov
  - pip install tox-travis
script:
  - tox
after_success:
  - codecov
